apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  containers:
  - name: nginx1
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: almalinux
    image: nginx:1.14.2
    ports:
    - containerPort: 80