apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx_app
  ports:
  - name: nodeport
    protocol: TCP
    port: 80
    targetPort: 80
    nodeport: 32768